#!/bin/bash
#
#  kcoda  - simplfied kcoda script
#

# RCGUI
echo "Killing rcgui"
pkill -f org.jlab.coda.afecs.ui.rcgui.RcGuiApplication

# PEBs and ROCs
kill_remotes.sh


# PLATFORM
echo "Killing platform"
pkill -f org.jlab.coda.afecs.platform.APlatform
