#!/bin/bash
#
# startCoda script for UVA GEM Cleanroom DAQ
#
XPOS=1000

pidlist=`pgrep platform; pgrep rcgui; pgrep coda_emu_peb`
if [[ "$pidlist" != "" ]] ; then
   echo $pidlist
    echo "coda is already running, are you sure you want to start a new coda? this will kill the previous process."
    read -p "Input Y or y to start a new coda:  " choice
    echo $choice
    if [ "$choice" != "y" -a "$choice" != "Y" ] ; then
	exit
    fi
fi

kcoda

xterm -geometry 60x5+${XPOS}+0 -T "platform" -bg "red" \
      -e /bin/bash -c "platform" &
sleep 8
xterm -geometry 60x25+${XPOS}+375 -T "Event Builder" -bg "green" \
      -e /bin/bash -c "PEB_eel124gemdaq" &
xterm -geometry 60x5+${XPOS}+250 -T "rcgui" -bg "yellow" \
      -e /bin/bash -c "rcgui" &

xterm -ls -n ROCcrate0 -title ROCcrate0--hallavme14pc \
      -bg white -fg black -sb -geometry 105x16+0+0 \
      -e ROC_hallavme14pc &

xterm -ls -n ROCcrate1 -title ROCcrate1--sbsvme25 \
      -bg white -fg black -sb -geometry 105x16+0+300 \
      -e ROC_sbsvme25 &

xterm -ls -n ROCcrate2 -title ROCcrate2--sbsvme30 \
      -bg white -fg black -sb -geometry 105x16+0+600 \
      -e ROC_sbsvme30 &
